server:
  port: 4444

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      routes:
        - id: cart-service
          uri: http://localhost:3333/
          predicates:
            - Path=/cart
        - id: product-service
          uri: http://localhost:2222/
          predicates:
            - Path=/**